name: Merge to main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build AzureTableStorageMigrator.csproj --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
    - name: Publish AzureTableStorageMigrator To Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: AzureTableStorageMigrator.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
